apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: v1
kind: Pod
metadata:
  name: currency-{{ .Values.CurrencyCode }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.CurrencyCode }}-microservice
    version: {{ .Values.Version }}
spec:
  containers:
  - name: currency-{{ .Values.Country }}
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text= feature available in {{ .Values.Country }}"
    - "-listen=:{{ .Values.Port }}"